# Generated by Django 5.0.2 on 2024-02-15 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'The title must be between 3 and 100 characters long.')]),
        ),
    ]
