# Generated by Django 5.0.2 on 2024-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('HU', 'Human'), ('FI', 'Finantial'), ('MA', 'Material'), ('TE', 'Technical')], default='MA', max_length=2)),
            ],
        ),
    ]
