In [1]:
import pandas as pd

In [2]:
data_frame = pd.read_csv("data.csv")
data_frame.head()

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

How many elements does this dataframe has? Data info

In [3]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


What is the duration of the index 123? Acceding an index

In [4]:
data_frame.loc[123, "Duration"]

60

What is the highest possible calories of a index?

In [5]:
data_frame.max() # Max values in each column

Duration     300.0
Pulse        159.0
Maxpulse     184.0
Calories    1860.4
dtype: float64

In [6]:
data_frame["Calories"].max() # Max value in a specific column

1860.4

In [7]:
data_frame.describe() # Describes the data

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.800000
std     42.299949   14.510259   16.450434   266.377134
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

Which of the following indexes 89, 126, 111, 3, 156 have a Pulse of 98 and a Calorie of 271 ?

In [8]:
data_frame.loc[[89, 125, 111, 3, 156]] # With loc you can pass a list of multiple indexes and see their value

Duration  Pulse  Maxpulse  Calories
89         20     83       107      50.3
125        60     98       122     271.0
111        45    107       124     275.0
3          45    109       175     282.4
156        60     97       131     270.4

What is the index with the Maxpulse of 182?

In [9]:
data_frame.loc[data_frame["Maxpulse"] == 182]

Duration  Pulse  Maxpulse  Calories
80        30    159       182     319.2

Sort the max pulses by descending, take 10 samples

In [30]:
data_frame.sort_values(by=["Maxpulse"], ascending=False).head(10)

Duration  Pulse  Maxpulse  Calories     Ratio
109       210    137       184    1860.4  1.343066
80         30    159       182     319.2  1.144654
54         30    136       175     238.0  1.286765
3          45    109       175     282.4  1.605505
58         20    153       172     226.4  1.124183
94         20    150       171     127.4  1.140000
85         30    151       170     300.1  1.125828
144        60    136       170     470.2  1.250000
122        60    119       169     336.7  1.420168
81         45    149       169     344.0  1.134228

What is the most common Calorie?

In [11]:
data_frame["Calories"].mode()

0    300.0
Name: Calories, dtype: float64

In [15]:
data_frame["Calories"].value_counts().head(10) # Counting the values

Calories
300.0    5
500.0    3
387.6    2
500.4    2
300.1    2
243.0    2
400.0    2
275.0    2
180.1    2
270.4    2
Name: count, dtype: int64

What is the lowest pulse with duration 60?

In [20]:
data_frame.loc[data_frame["Duration"] == 60].min()

Duration     60.0
Pulse        92.0
Maxpulse    101.0
Calories    215.2
dtype: float64

Index where Duartion is equal to 60 and Calories 479

In [25]:
data_frame.loc[
  (data_frame["Duration"] == 60) &
  (data_frame["Calories"] == 479)
]

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

Create a column called Ratio (Max pulse / Pulse)

In [37]:
data_frame["Ratio"] = data_frame["Maxpulse"] / data_frame["Pulse"]
data_frame.head()

Duration  Pulse  Maxpulse  Calories     Ratio
0        60    110       130     409.1  1.181818
1        60    117       145     479.0  1.239316
2        60    103       135     340.0  1.310680
3        45    109       175     282.4  1.605505
4        45    117       148     406.0  1.264957

What is the pulse of indexes with 60 duration

In [64]:
data_frame.loc[data_frame["Duration"] == 60]

# for i in range(len(data_frame)):
#   if (data_frame.iloc[i]["Duration"] == 60):
#     print(data_frame.iloc[i]["Pulse"])

data_frame["Duration"].describe()

count    169.000000
mean      63.846154
std       42.299949
min       15.000000
25%       45.000000
50%       60.000000
75%       60.000000
max      300.000000
Name: Duration, dtype: float64